### ISSUE TITLE
Petits détails pour la compilation sous OSX

### ISSUE THREAD

**Issue by MrXedac** [arnaudcoj/pji_full_metal_planete#2]
Hello,

Je viens de compiler votre projet sous macOS, quelques petites précisions que vous pourriez rajouter dans le Readme - en tout cas, pour la compil macOS : 
- dans la configuration de la toolchain utilisée pour compiler api/interface/game (Settings/Build Settings dans Codelite), décocher "Pass object list to the linker via file" (manifestement ça doit passer avec une toolchain GNU, mais l'archiveur BSD a quelques soucis avec la syntaxe @"file.txt")
- pour l'installation de SFML, une installation en /usr/local/{include,lib} tourne, mais il faut quand même les frameworks du dossier extlibs de la distribution SFML (notamment vorbisenc) dans /Library/Frameworks (j'ignore encore pourquoi ça n'est pas géré en /usr/local/* de la même façon)

En dehors de ça tout fonctionne. Sympathique projet :)

**Comment by TristanCms** [comment]
Merci pour ces retours sur le projet. Je viens de tester l'installation sous OSX. Effectivement, j'ai eu besoin de réaliser ces manipulations pour build le projet. J'ajoute ce qu'il faut au Readme :)
